---

- hosts: pod0
  become: true
  tasks:
    - name: Install unzip
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Download and extract WordPress template
      unarchive:
        src: https://wordpress.org/latest.zip
        dest: /var/www/
        remote_src: yes
        owner: root
        group: root
        mode: 0755